In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sympy as sp

from scipy import constants, stats, optimize
from scipy.sparse import csr_matrix

np.random.seed(42)
print("Libraries imported successfully.")

pd.set_option("display.float_format",lambda x: f"{x:,.2f}")

Libraries imported successfully.

In [23]:
df = pd.read_csv("../data/loan_test.csv")
df.head()

,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area
0,Male,Yes,0,Graduate,No,572000,0,11000000,360.0,1.0,Urban
1,Male,Yes,1,Graduate,No,307600,150000,12600000,360.0,1.0,Urban
2,Male,Yes,2,Graduate,No,500000,180000,20800000,360.0,1.0,Urban
3,Male,Yes,2,Graduate,No,234000,254600,10000000,360.0,NaN,Urban
4,Male,No,0,Not Graduate,No,327600,0,7800000,360.0,1.0,Urban

In [24]:
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

Rows: 367
Columns: 11

In [25]:
df.dtypes

Gender                    str
Married                   str
Dependents                str
Education                 str
Self_Employed             str
Applicant_Income        int64
Coapplicant_Income      int64
Loan_Amount             int64
Term                  float64
Credit_History        float64
Area                      str
dtype: object

In [27]:
df.info(

)

<class 'pandas.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Gender              356 non-null    str
 1   Married             367 non-null    str
 2   Dependents          357 non-null    str
 3   Education           367 non-null    str
 4   Self_Employed       344 non-null    str
 5   Applicant_Income    367 non-null    int64
 6   Coapplicant_Income  367 non-null    int64
 7   Loan_Amount         367 non-null    int64
 8   Term                361 non-null    float64
 9   Credit_History      338 non-null    float64
 10  Area                367 non-null    str
dtypes: float64(2), int64(3), str(6)
memory usage: 31.7 KB

In [30]:
df.describe()

,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History
count,367.00,367.00,367.00,361.00,338.00
mean,"480,559.95","156,957.77","13,427,792.92",342.54,0.83
std,"491,068.54","233,423.21","6,296,142.57",65.16,0.38
min,0.00,0.00,0.00,6.00,0.00
25%,"286,400.00",0.00,"10,000,000.00",360.00,1.00
50%,"378,600.00","102,500.00","12,500,000.00",360.00,1.00
75%,"506,000.00","243,050.00","15,750,000.00",360.00,1.00
max,"7,252,900.00","2,400,000.00","55,000,000.00",480.00,1.00

In [31]:
df.isnull().sum()

Gender                11
Married                0
Dependents            10
Education              0
Self_Employed         23
Applicant_Income       0
Coapplicant_Income     0
Loan_Amount            0
Term                   6
Credit_History        29
Area                   0
dtype: int64

In [32]:
print("Missing values in each column:\n",df.isnull().sum())
print("\nTotl Missing values:",df.isnull().sum().sum)

Missing values in each column:
 Gender                11
Married                0
Dependents            10
Education              0
Self_Employed         23
Applicant_Income       0
Coapplicant_Income     0
Loan_Amount            0
Term                   6
Credit_History        29
Area                   0
dtype: int64

Totl Missing values: <bound method Series.sum of Gender                11
Married                0
Dependents            10
Education              0
Self_Employed         23
Applicant_Income       0
Coapplicant_Income     0
Loan_Amount            0
Term                   6
Credit_History        29
Area                   0
dtype: int64>

In [4]:
arr1 = np.array([3,4,7,9,5])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr1.ndim,arr2.ndim,arr3.ndim)
print(arr1.shape,arr2.shape,arr3.shape)

1 2 3
(5,) (2, 3) (2, 2, 3)

In [7]:
df1 = pd.read_csv("../data/retail_sales_dataset.txt")
df1.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [8]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [9]:
df1.describe()

       Transaction ID      Age  Quantity  Price per Unit  Total Amount
count        1,000.00 1,000.00  1,000.00        1,000.00      1,000.00
mean           500.50    41.39      2.51          179.89        456.00
std            288.82    13.68      1.13          189.68        560.00
min              1.00    18.00      1.00           25.00         25.00
25%            250.75    29.00      1.00           30.00         60.00
50%            500.50    42.00      3.00           50.00        135.00
75%            750.25    53.00      4.00          300.00        900.00
max          1,000.00    64.00      4.00          500.00      2,000.00

In [11]:
df1.shape

(1000, 9)